version: '3'

services:
  ubuntu_14.10:
    build:
      context: ./Ubuntu14.10
      dockerfile: Dockerfile
    container_name: c1
    ports:
      - "8080:8080"

  ubuntu_16.10:
    build:
      context: ./Ubuntu16.10
      dockerfile: Dockerfile
    container_name: c2
    ports:
      - "8081:8080"

  ubuntu_18.10:
    build:
      context: ./Ubuntu18.10
      dockerfile: Dockerfile
    container_name: c3
    ports:
      - "8082:8080"

  ubuntu_20.10:
    build:
      context: ./Ubuntu20.10
      dockerfile: Dockerfile
    container_name: c4
    ports:
      - "8083:8080"

